apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-registry
  namespace: koad-registry
  labels:
    app: private-registry
    koad-scenario: S12
    mitre-attck: T1525
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-registry
  template:
    metadata:
      labels:
        app: private-registry
    spec:
      containers:
        - name: registry
          image: koad/private-registry:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry
      volumes:
        - name: registry-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: private-registry
  namespace: koad-registry
  labels:
    koad-scenario: S12
spec:
  type: NodePort
  selector:
    app: private-registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
